apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo
spec:
  replicas: 2

  strategy:            
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: aks-demo

  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      containers:
      - name: aks-demo
        image: vkraftacr123.azurecr.io/aks-demo-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000