apiVersion: v1
kind: Service
metadata:
  name: aks-demo-service
  namespace: AKS-ROLL-OUT-DEMO
spec:
  type: ClusterIP
  selector:
    app: aks-demo
  ports:
    - port: 80
      targetPort: 5000